[package]
name = "ruscom"
version = "0.1.0"
edition = "2021"
description = "A C++ compiler prototype written in Rust (project scaffold)"
authors = ["ekas <ekas@example.com>"]

[dependencies]
clap = { version = "4.3", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
